#!/bin/sh

if [ "$BRANDING" != "default" ]; then
  envsubst "\${API_ENDPOINT} \${WS_ENDPOINT} \${BRANDING}" < /etc/nginx/conf.d/app-web-branding.conf.template > /etc/nginx/conf.d/app-web.conf
else
  envsubst "\${API_ENDPOINT} \${WS_ENDPOINT}" < /etc/nginx/conf.d/app-web.conf.template > /etc/nginx/conf.d/app-web.conf
fi

exec "$@"
